### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by khuonghoanghuy** [Joalor64GH/Rhythmo-SC#8]
A task list issues
# v1.0.0 List Track
- [ ] Remake the note assets, with note splash (optional)
- [ ] Make a better charting menu
- [ ] Make a editor for modding (like chart editior) (optional)
- [x] Fix Controls settings
- [x] Make a wiki
- [ ] Fix font for some language can't display correctly

**Comment by khuonghoanghuy** [comment]
wait i just found ur TODO.md so i close this issues
